//! Statement-specific analyzers.

pub mod attribute_analyzer;
pub mod break_analyzer;
pub mod class_analyzer;
pub mod continue_analyzer;
pub mod scope_analyzer;
pub mod do_analyzer;
pub mod echo_analyzer;
pub mod expression_stmt_analyzer;
pub mod for_analyzer;
pub mod foreach_analyzer;
pub mod function_analyzer;
pub mod global_analyzer;
pub mod else_analyzer;
pub mod elseif_analyzer;
pub mod if_conditional_analyzer;
pub mod if_else_analyzer;
pub mod loop_;
pub mod loop_analyzer;
pub mod return_analyzer;
pub mod static_analyzer;
pub mod switch_case_analyzer;
pub mod switch_analyzer;
pub mod try_analyzer;
pub mod unset_analyzer;
pub mod while_analyzer;
